### ISSUE TITLE
Integrate with nix-emacs-ci

### ISSUE THREAD

**Issue by DamienCassou** [akirak/emacs-package-checker#1]
@purcell made the [nix-emacs-ci project](https://github.com/purcell/nix-emacs-ci) which provides several Emacs packages to use for CI environments.

There is probably a way to make both projects easy to setup together.

**Comment by akirak** [comment]
Thank you for the pointer. I am aware of the project and looking for a way to integrate it.

My solution already works with nix-emacs-ci on GitHub Actions as in [this nix expression](https://github.com/akirak/poly-vue/blob/scratch/github-action/default.nix) and [this workflow](https://github.com/akirak/poly-vue/blob/scratch/github-action/.github/workflows/test.yml). I probably need to refine the API. Any comments are welcome.

**Comment by DamienCassou** [comment]
Good job. You may close the issue.
