### ISSUE TITLE
Option to enable package-lint-main-file for package-lint

### ISSUE THREAD

**Issue by ericdallo** [akirak/emacs-package-checker#10]
There's a configuration for `package-list` to specify the main-file for multiple-packages called `package-lint-main-file` where `lsp-dart` configures it currently [here](https://github.com/emacs-lsp/lsp-dart/blob/master/Makefile#L16).

With this option enable, package-lint doesn't check headers for other files, only for the main-file as implemented [here](https://github.com/purcell/package-lint/pull/173).

I think we should enable this option when the user select the multi-package option on the start.

**Comment by akirak** [comment]
I'm aware of the option, and I added it as `mainFile` field in the package configuration, but my package-lint usage seems to be wrong (https://github.com/melpa/melpa/pull/6918#issuecomment-633747312). I will check it soon. Thank you for the pointer.

> I think we should enable this option when the user select the multi-package option on the start.

AFAIK this option is intended for multi-file packages (i.e. packages consisting of multiple source files), and not for multi-package repositories.

**Comment by ericdallo** [comment]
Sorry, that's what I wanted to say, multi-file packages ;)

**Comment by akirak** [comment]
This is now properly supported. `package-lint` bundled in `melpa-check` (more precisely, Nixpkgs) was a little old, so it behaved differently.

**Comment by ericdallo** [comment]
Confirmed that it was fixed, thanks
