### ISSUE TITLE
Package dependencies are too old

### ISSUE THREAD

**Issue by ericdallo** [akirak/emacs-package-checker#12]
When running the `melpa-check-run-all` I have some byte-compile-errors (weird, that we don't have on the current CI), but the problem is that the program exists with an too many arguments error on mkdir.

```
Running byte-compile on lsp-dart.el lsp-dart-closing-labels.el lsp-dart-code-lens.el lsp-dart-dap.el lsp-dart-devtools.el lsp-dart-flutter-colors.el lsp-dart-flutter-daemon.el lsp-dart-flutter-fringe.el lsp-dart-flutter-widget-guide.el lsp-dart-outline.el lsp-dart-test-support.el lsp-dart-utils.el ...
[Treemacs] Warning: couldn't find hl-line-mode's background color for icons, falling back on unspecified-bg.
[Treemacs] Python3 not found, advanced git-mode and directory flattening features will be disabled.

In toplevel form:
lsp-dart.el:34:1: Error: Symbol's function definition is void: dap-utils-github-extension-setup-function

In toplevel form:
lsp-dart-code-lens.el:27:1: Error: Symbol's function definition is void: dap-utils-github-extension-setup-function

In toplevel form:
lsp-dart-dap.el:369:1: Error: the following functions are not known to be defined: dap-utils-github-extension-setup-function, dap-request
[Treemacs] Warning: couldn't find hl-line-mode's background color for icons, falling back on unspecified-bg.
[Treemacs] Python3 not found, advanced git-mode and directory flattening features will be disabled.

In toplevel form:
lsp-dart-outline.el:25:1: Error: Symbol's function definition is void: dap-utils-github-extension-setup-function

In toplevel form:
lsp-dart-test-support.el:26:1: Error: Symbol's function definition is void: dap-utils-github-extension-setup-function
Byte-compilation failed in at least one of lsp-dart.el lsp-dart-closing-labels.el lsp-dart-code-lens.el lsp-dart-dap.el lsp-dart-devtools.el lsp-dart-flutter-colors.el lsp-dart-flutter-daemon.el lsp-dart-flutter-fringe.el lsp-dart-flutter-widget-guide.el lsp-dart-outline.el lsp-dart-test-support.el lsp-dart-utils.el
builder for '/nix/store/m4f18f9vlpy71hc88fwyccbr4232zh51-lsp-dart-byte-compile.drv' failed with exit code 5
error: build of '/nix/store/m4f18f9vlpy71hc88fwyccbr4232zh51-lsp-dart-byte-compile.drv' failed

builder for '/nix/store/5163rba8ma0jy3yqq8b636c30nkahr9b-emacs-lsp-dart-1.11.5.drv' failed with exit code 126; last 2 log lines:
  unpacking sources
  /nix/store/vilh5ays3ymz3xkwk0fri2a70lha7pfc-stdenv-linux/setup: line 81: /nix/store/bgvd279hrb53i3ah2mi0nf8jp6g6g6g9-coreutils-8.31/bin/mkdir: Argument list too long
cannot build derivation '/nix/store/82vll8r1cv7ih58x7lvv9c3ha75wa3kn-emacs-snapshot-with-packages-08408b13.drv': 1 dependencies couldn't be built
error: build of '/nix/store/82vll8r1cv7ih58x7lvv9c3ha75wa3kn-emacs-snapshot-with-packages-08408b13.drv' failed

Error: 2/4 of the tasks have failed:
Exit code 100 from command "nix-shell --quiet /home/greg/dev/lsp-dart/.melpa-check -A shellWithoutBuild --run 'set -e; for p in ${packages[*]}; do
melpaCheckNixBuild -A byte-compile.$p
done'"
Exit code 100 from command "nix-shell --quiet /home/greg/dev/lsp-dart/.melpa-check -A shellWithoutBuild --run 'set -e; for p in ${packages[*]}; do
melpaCheckNixBuild --no-build-output -A prepareAllTests.$p >/dev/null && melpaCheckNixShell -A allTests.$p
done'"

Compilation exited abnormally with code 1 at Tue May 26 20:04:44
```

**Comment by ericdallo** [comment]
The error keeps happening even commenting the function from the byte-compile error above

**Comment by akirak** [comment]
This is not a bug of `melpa-check` itself but an expected behavior. I received the same feedback from riscy almost every time I sent a PR to MELPA, so I suppose it is a common mistake. The previous versions of this program didn't produce those errors, but I [fixed](https://github.com/akirak/melpa-check/issues/11) it to produce the same result as riscy did on the PR review: https://github.com/melpa/melpa/pull/6918#issuecomment-633747312 You have to address the issue for yourself.

If dap is an optional dependency, you can fix it by inserting `declare-function`, e.g.

```emacs-lisp
(declare-function dap-utils-github-extension-setup-function "ext:dap-mode")
```

Otherwise, you have to add it as a required dependency:

1. Add the external package to `dependencies` in your package configuration (`packages.dhall`).
2. Add the package to `Package-Requires` header as well to prevent a `package-lint` warning
3. `require` it in your source files

**Comment by akirak** [comment]
I have changed the issue title for referencing.

**Comment by ericdallo** [comment]
Yeah, but `dap-mode` is already on [Package-Requires Header](https://github.com/emacs-lsp/lsp-dart/blob/master/lsp-dart.el#L4) and already required on [the source](https://github.com/emacs-lsp/lsp-dart/blob/master/lsp-dart-dap.el#L23-L24). This error does not happen when I run a byte-compile from the [currently CI](https://github.com/emacs-lsp/lsp-dart/blob/master/Makefile#L24-L30).

I was expecting that I didn't need to add dependencies on `packages.dhall`, so every time I need to add a new dependency to my project, I'll need to add to `packages.dhall` too :pensive: ?
I thought that `melpa-check` would handle this automatically reading the `Package-Requires` header.

**Comment by akirak** [comment]
Sorry, the Emacs frontend reads dependencies from `Package-Requires` header when it generates `packages.dhall`, but when you add a new dependency, you have to add it to the dhall configuration. It doesn't read the header at runtime, though it may be technically possible. 

> the problem is that the program exists with an too many arguments error on mkdir.

The command line looks ugly, but it is an actual command that `melpa-check` use for linting. Maybe I had better come up with a cleaner output format.

**Comment by akirak** [comment]
Again, the issue was that dap-mode used by `melpa-check` was so old that it didn't contained the macro. It depends on release 20.03 of `nixpkgs` with a relatively old set of Emacs packages. Nixpkgs regularly updates its Emacs package set [like this](https://github.com/NixOS/nixpkgs/commit/8c65a2f1de8b5c9afddd217f3ed425eae5e1399e#diff-b1864d4e308e56ef358dd33142771718). 

I changed the program to use the unstable version of `nixpkgs` for a fresher set of packages. You can also update it using `niv update nixpkgs-unstable`. It now passes the set of Emacs packages as an argument, so you can override some packages by editing `default.nix` in your project. 

After reinitializing your project, the byte-compilation errors on `lsp-dart` disappears.

I was able to reproduce the too-many-arguments error, but I haven't found out a solution yet. I will investigate it soon.

**Comment by ericdallo** [comment]
Thanks @akirak for the great effort, I'll try again.
Is there any way for melpa-check use the MELPA packages instead the version of the unstable nixpkgs?

**Comment by akirak** [comment]
Nixpkgs provides packages from ELPA, MELPA, etc., and I currently use MELPA packages for dependencies (maybe I'll have to add ELPA later), but it is based on a specific snapshot of the package database.

`melpa-check` now also accepts `emacsPackages` argument, so you can override/add certain packages in default.nix using a procedure described in [this comment](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/emacs/wrapper.nix#L23). To define a new package, use `melpaBuild` function in Nix. This is what `melpa-check` internally does.

It is possible to download packages from MELPA before running `byte-compile` and tests, but this has some limitations. Nixpkgs contains workarounds for some packages that involve a specific build process or native dependencies (defined in [this file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs-modes/melpa-packages.nix)). This will be critical for testing packages that depend on `emacsql-sqlite`, for example. ~~Also, Nix doesn't allow internet connection inside `nix-build`, so package installation has to be run inside `nix-shell`, which limits the power of Nix (and requires a lot of changes in `melpa-check`).~~ Therefore I didn't choose this path.

**Comment by terlar** [comment]
I would recommend using the https://github.com/nix-community/emacs-overlay which updates the packages every 4 hours. It will be fresh packages and have the nix package fixes.

**Comment by akirak** [comment]
@terlar Thank you, that looks very useful!

**Comment by ericdallo** [comment]
Yeah, I use my emacs on NixOS from https://github.com/nix-community/emacs-overlay too :)

**Comment by akirak** [comment]
Implemented this feature. Thanks, @terlar!

@ericdallo 
Now `melpa-check` accepts `emacs-overlay` argument for overriding Emacs packages. You have to update `default.nix` in `lsp-dart` [like this](https://github.com/akirak/lsp-dart/blob/melpa-check-ci/.melpa-check/default.nix) and update `melpa-check` (`niv update melpa-check`).
