### ISSUE TITLE
Name suggestions

### ISSUE THREAD

**Issue by akirak** [akirak/emacs-package-checker#18]
One active package author in the Emacs community displayed his opposition to the name `melpa-check`. Now I am taking this idea into account seriously. Considering the fact that I seem to be the only person using it in production at present, it will be the best time for the change.

In the beginning, this project was named `emacs-package-checker` (three words), and now it is `melpa-check` (two words). I really don't have an idea for a unique name, but a single word looks inevitable.

Despite its name, `melpa-check` doesn't have to relate to MELPA. It takes MELPA recipes as part of its input, and the recipe format is a great, well-thought invention of the history, but the situation may change in the future. I shouldn't insist on the name. Besides, this project is experimental and opinionated.

Because the project is half about Nix, I think it would be important to give a name containing the character "n". I came up with a few ideas:

- `nelpa`, where n would stand both for Nix and next, but it is not a package archive.
- `nite`, which is an acronym for NIx Tooling for Emacs. The problem is that the word is also a verb which means to refuse/deny, which has a negative connotation. It sounds like it was rejected by the Emacs community (or I left them).

Neither is good. I would like to hear a better idea about naming.

**Comment by ericdallo** [comment]
I see this package as a Emacs package checker or linter, it's something that people will want to use in a CI or local for checking for byte-compile errors, checkdoc, package-lint issues, and tests, so I think something like `checker.el` or `echecker` would have a great name impact on community :)

**Comment by akirak** [comment]
@ericdallo Thanks for your suggestion. `echecker` describes what the program does. That's pretty straightforward.

Actually, I was looking for a subtle, vague name. It should be something like a code name, but can be used throughout its life, not for a specific version. I came up with "Nelson" because of Nix + Emacs Lisp, which is not subtle. This is just a random thought, and I don't have a strong insist on it. 

Simply `echecker` may be good. I will wait for a while before I make a decision.

**Comment by ericdallo** [comment]
yeah, IMO nix is just an implementation detail of this package, we can in the future (I hope not) change nix to another tool that makes more sense.
One thing that should never change on this package, is that it's made for Emacs and to check/lint/etc, so `echecker` or `elinter` or something like that could be a good fit :)

**Comment by akirak** [comment]
@ericdallo Thanks, I will take it into account. 

No single person is as wise as a crowd of smart people, and I am definitely not as good as the Nix community. I think I have to learn the current common practices for using Nix before building something on top of it, so I will change the current version to "maintenance mode". I may add some experimental features such as melpazoid-integration, but **it is not meant for general adoption**. I will start using a new name in the next iteration with possibly a new API.

Meanwhile, someone else may be able to create a better implementation of the idea. It might be more desirable to cooperate with (or contribute to) such people than to working on my own.

**Comment by akirak** [comment]
@ericdallo I have been working on `elinter`, but your primary suggestion was `echecker`. This was my mistake. It is currently referred from only one other repository, and I can rename the project from now. 

Nonetheless, I've just noticed that `elinter` is easier to type than `echecker` on QWERTY keyboard (and also shorter), so I'd prefer `elinter`. What do you think?

**Comment by ericdallo** [comment]
haha what you prefer, it's your project :p
For me both are good

**Comment by akirak** [comment]
Thanks, I'll stick with `elinter`, because it's easier to type for me. Thank you for your suggestions.
