### ISSUE TITLE
Support for *.el on targetFiles

### ISSUE THREAD

**Issue by ericdallo** [akirak/emacs-package-checker#4]
Is there any way to make `targetFiles` optional and it finds `*.el` files to lint?

**Comment by akirak** [comment]
See https://github.com/akirak/melpa-check/issues/5#issuecomment-618132737

**Comment by akirak** [comment]
I didn't implement this feature in the new version, but indeed this is a good idea, as the MELPA recipe provides the default file patterns.

I have implemented a similar feature for finding buttercup tests through the extglob of bash. It would be possible to provide the same feature for source files. However, you will probably have to specify an exclude pattern at the same time. It is sufficient to exclude duplicates in test files from source files?

**Comment by akirak** [comment]
I am currently working on `v4` branch. It uses MELPA recipes to specify source files, so it accepts glob patterns.
