### ISSUE TITLE
Can't byte-compile multiple files

### ISSUE THREAD

**Issue by ericdallo** [akirak/emacs-package-checker#5]
I'm trying to configure [`lsp-dart`](https://github.com/emacs-lsp/lsp-dart) to use this nice package :)
This is what I'm trying:

`default.nix`
```nix
{ pkgs ? import <nixpkgs> {},
  emacs ? (import (pkgs.fetchFromGitHub {
    owner = "purcell";
    repo = "nix-emacs-ci";
    rev = "53e8f05a66addd520e1feec23eabd6a8a86ee47f";
    sha256 = "0v524dsckbhn0y3ywj7dd1a74p6mi7gqz7xdpkzy3l8c2pvpy1sy";
  })).emacs-26-3
}:
let
  check-package = import (builtins.fetchTarball "https://github.com/akirak/emacs-package-checker/archive/v1.tar.gz");
in check-package {
  inherit emacs pkgs;
  name = "emacs-lsp-dart";
  src = ./.;
  targetFiles = [
    "lsp-dart-project.el"
    "lsp-dart-flutter-colors.el"
    "lsp-dart-flutter-fringe.el"
    "lsp-dart-flutter-widget-guide.el"
    "lsp-dart-test-support.el"
    "lsp-dart-dap.el"
    "lsp-dart.el"
  ];
  emacsPackages = epkgs: (with epkgs.melpaPackages; [
    f
    ht
    dash
    dart-mode
    lsp-mode
    lsp-treemacs
    dap-mode
    pkg-info
  ]);
}
```

When I run `nix-build --no-out-link -A byte-compile`, it byte-compile successfully all files but `lsp-dart.el` which requires `lsp-dart-project.el`

`output`
```bash
these derivations will be built:
  /nix/store/v7ksr4b8jc4bjnhbplcb9ci6fz59pcwy-emacs-lsp-dart-byte-compile.drv
building '/nix/store/v7ksr4b8jc4bjnhbplcb9ci6fz59pcwy-emacs-lsp-dart-byte-compile.drv'...
----------------------------------------------------------------------
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
----------------------------------------------------------------------
Running byte-compile...

In toplevel form:
lsp-dart-flutter-fringe.el:30:1:Error: Cannot open load file: No such file or directory, lsp-dart-flutter-colors

In toplevel form:
lsp-dart-test-support.el:29:1:Error: Cannot open load file: No such file or directory, lsp-dart-project

In toplevel form:
lsp-dart-dap.el:31:1:Error: Cannot open load file: No such file or directory, lsp-dart-project
[Treemacs] Warning: coudn't find default background color for icons, falling back on #2d2d31.
[Treemacs] Warning: couldn't find hl-line-mode's background color for icons, falling back on #2d2d31.
[Treemacs] Python3 not found, advanced git-mode and directory flattening features will be disabled.

In toplevel form:
lsp-dart.el:33:1:Error: Cannot open load file: No such file or directory, lsp-dart-project
builder for '/nix/store/v7ksr4b8jc4bjnhbplcb9ci6fz59pcwy-emacs-lsp-dart-byte-compile.drv' failed with exit code 1
error: build of '/nix/store/v7ksr4b8jc4bjnhbplcb9ci6fz59pcwy-emacs-lsp-dart-byte-compile.drv' failed
```

**Comment by akirak** [comment]
Thank you for your comment. 

I am sorry for your effort, but the branch is no longer developed. 

I am currently working extensively on this [v3](https://github.com/akirak/melpa-check/tree/v3) branch. Its API is subject to change, but it is already used in my [org-multi-wiki](https://github.com/akirak/org-multi-wiki/) project. I also plan on adding a CLI for simplifying the action configuration as well as an Emacs Lisp frontend which will let you interactively configure packages. It will take some time until it is officially released.

Could you please wait until I announce its initial release? For now, you can copy the configuration from [org-multi-wiki](https://github.com/akirak/org-multi-wiki/) (though it is likely to change in the future) or use other solution like [makem](https://github.com/alphapapa/makem.sh/). Thanks.

**Comment by ericdallo** [comment]
Thank you for your quick anwser, I configured a CI using the old [Makefile way](https://github.com/emacs-lsp/lsp-dart/blob/master/Makefile#L21).

I'll wait for the v3 release anxiously :)

**Comment by akirak** [comment]
After a month of work, it's almost finished.

Now it's distributed as an Emacs package. First install `nix` and `niv`, and then use an Emacs command to initialize configuration files.

**Comment by akirak** [comment]
I have sent [a pull request](https://github.com/melpa/melpa/pull/6918) to MELPA. Hopefully, it will be available as an Emacs package on MELPA soon.

**Comment by ericdallo** [comment]
Thanks! I'll certainly try to use this on `lsp-dart` and if it works nice, on other emacs-lsp repos :)
