### ISSUE TITLE
Ignore cask files on melpa-check-project-init

### ISSUE THREAD

**Issue by ericdallo** [akirak/emacs-package-checker#8]
Congratulations for the awesome command `melpa-check-project-init`, it's very useful!

[Cask](https://github.com/cask/cask) is used for elisp project management.

![image](https://user-images.githubusercontent.com/7820865/82853835-21c8f300-9edd-11ea-8e92-6ce1f269bc68.png)

**Comment by akirak** [comment]
Maybe I'll ignore all dot files and dot directories. Thank you for the compliment.

**Comment by akirak** [comment]
It's implemented. Thanks.
